"""Application constants"""

# Validation limits
MIN_NAME_LENGTH = 2
MAX_NAME_LENGTH = 50
MAX_DESCRIPTION_LENGTH = 200
MIN_SKILLS_COUNT = 1
MAX_SKILLS_COUNT = 3  # For participants
MAX_SKILLS_COUNT_UNLIMITED = 10  # For teams

# Rate limiting
MAX_INVITATIONS_PER_DAY = 5
REQUESTS_PER_MINUTE = 20
THROTTLE_TIME_WINDOW = 60  # seconds

# Cleanup intervals
CLEANUP_EXPIRED_INVITATIONS_HOURS = 72
CLEANUP_INACTIVE_USERS_DAYS = 30
CLEANUP_INTERVAL_MINUTES = 60

# Cold start threshold
COLD_START_USER_COUNT = 10

# Pagination
SEARCH_RESULTS_PER_PAGE = 10
